/* Auto-generated kernel compatibility configuration */
/* Kernel version: 6.18.0-061800rc2-generic */
/* Generated on: Sat Oct 25 12:42:05 CEST 2025 */

#ifndef BACKPORTS_KERNEL_COMPAT_CONFIG_H
#define BACKPORTS_KERNEL_COMPAT_CONFIG_H

/* Kernel version information */
#define BACKPORTS_KERNEL_VERSION_MAJOR 6
#define BACKPORTS_KERNEL_VERSION_MINOR 18
#define BACKPORTS_KERNEL_VERSION_PATCH 0
#define BACKPORTS_KERNEL_VERSION_CODE 397824
#define BACKPORTS_KERNEL_VERSION_STRING "6.18.0-061800rc2-generic"

/* Platform detection */
#define BACKPORTS_IS_ANDROID_KERNEL 0
#define BACKPORTS_IS_MOBILE_PLATFORM 0
#define BACKPORTS_IS_LTS_KERNEL 0

/* Feature availability */
#define BACKPORTS_ANDROID_OPTIMIZED 0
#define BACKPORTS_MOBILE_PLATFORM 0
#define BACKPORTS_POWER_MANAGEMENT "advanced"
#define BACKPORTS_REGULATORY_API "v4"
#define BACKPORTS_HAS_CFG80211_FEATURES_SCAN_INFO_V2 1
#define BACKPORTS_HAS_CFG80211_FEATURES_CONNECT_TIMEOUT 1
#define BACKPORTS_HAS_CFG80211_FEATURES_NAN_SUPPORT 1
#define BACKPORTS_HAS_CFG80211_FEATURES_6GHZ_SUPPORT 1
#define BACKPORTS_HAS_CFG80211_FEATURES_EHT_SUPPORT 1
#define BACKPORTS_HAS_MAC80211_FEATURES_TXQ_SUPPORT 1
#define BACKPORTS_HAS_MAC80211_FEATURES_AIRTIME_FAIRNESS 1
#define BACKPORTS_HAS_MAC80211_FEATURES_HE_SUPPORT 1
#define BACKPORTS_HAS_MAC80211_FEATURES_MULTI_BSSID 1
#define BACKPORTS_HAS_MAC80211_FEATURES_EHT_SUPPORT 1
#define BACKPORTS_HAS_NETLINK_FEATURES_EXT_ACK 1
#define BACKPORTS_HAS_NETLINK_FEATURES_POLICY_VALIDATION 1
#define BACKPORTS_HAS_NETLINK_FEATURES_STRICT_VALIDATION 1
#define BACKPORTS_HAS_NETLINK_FEATURES_GENETLINK_V2 1
#define BACKPORTS_HAS_SKB_FEATURES_PUT_ZERO 1
#define BACKPORTS_HAS_SKB_FEATURES_PUT_DATA 1
#define BACKPORTS_HAS_SKB_FEATURES_LINEAR_DATA 1
#define BACKPORTS_HAS_SKB_FEATURES_FRAG_LIST 1
#define BACKPORTS_HAS_SKB_FEATURES_GSO_PARTIAL 1
#define BACKPORTS_TIMER_API "new"
#define BACKPORTS_HAS_WORKQUEUE_FEATURES_HIGHPRI 1
#define BACKPORTS_HAS_WORKQUEUE_FEATURES_POWER_EFFICIENT 1
#define BACKPORTS_HAS_WORKQUEUE_FEATURES_UNBOUND 1
#define BACKPORTS_HAS_WORKQUEUE_FEATURES_CPU_INTENSIVE 1

/* Compatibility shims required */

#endif /* BACKPORTS_KERNEL_COMPAT_CONFIG_H */